### ISSUE TITLE
Ansible error

### ISSUE THREAD

**Issue by vschwaberow** [swiftycloud/hkube#1]
Getting following error

[WARNING]:  * Failed to parse /Users/xxx/Documents/Sources/kubernetes/hkube/kubespray/inventory/mycluster/hosts.ini with ini plugin:
/Users/xxx/Documents/Sources/kubernetes/hkube/kubespray/inventory/mycluster/hosts.ini:4: Expected key=value host variable assignment, got: x.x.x.x.x

 [WARNING]: Unable to parse /Users/xxx/Documents/Sources/kubernetes/hkube/kubespray/inventory/mycluster/hosts.ini as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

Hosts are not found over the inventory. Any suggestions?

**Comment by bbelky** [comment]
Hi! Could you please share your config.json file?

**Comment by vschwaberow** [comment]
{
    "hcloud_token": "[redacted]",
    "hcloud_user_sshkey_name": "vsc",
    "hcloud_server_type": "cx11",
    "hcloud_location": "fsn1",
    "hcloud_name": "k8s",
    "hcloud_count": "6"
}%

Here it is.. Thanks for having a look into it.

**Comment by bbelky** [comment]
Hi @vschwaberow 
I have updated the tool. Issue was because of kubespray ansible playbook changes. Sorry fro delay(

**Comment by vschwaberow** [comment]
Many thanks. I will test it.
